
function findLanguage(ext){
    const map = {
        js: "javascript",
        jsx: "javascript",
        ts: "typescript",
        tsx: "typescript",
        py: "python",
        java: "java",
        c: "c",
        cpp: "cpp",
        cs: "csharp",
        rb: "ruby",
        go: "go",
        php: "php",
        html: "html",
        css: "css",
        scss: "scss",
        json: "json",
        xml: "xml",
        sh: "shell",
        md: "markdown",
        yaml: "yaml",
        yml: "yaml",
        sql: "sql",
        swift: "swift",
        kt: "kotlin",
        rs: "rust",
        dart: "dart",
        txt: "plaintext",
        h: "c",
        hpp: "cpp", 
        vb: "visualbasic",
        asm: "assembly",
        lua: "lua",  
        r: "r",
        pl: "perl",  
        sh: "shell",   
        bat: "batch",    
        csv: "csv",   
        mdx: "markdown",    
        json5: "json",
        coffee: "coffeescript",  
        elm: "elm",
        sql: "sql",
        vhdl: "vhdl",
        yml: "yaml",  
        tex: "latex",  
        csv: "csv",  
        xsl: "xsl",
    };

    return map[ext.toLowerCase()] || "plaintext";
}
